import { Card, CardContent } from "@/components/ui/card";
import { Sparkles, Shield, Users } from "lucide-react";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";

export default async function AboutPage() {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  return (
    <div className="flex flex-col min-h-screen bg-[#FAFAF9] text-slate-900 font-sans">
      <SiteHeader userSession={session} />

      {/* Main Content */}
      <main className="flex-grow container mx-auto max-w-4xl px-4 py-16 space-y-16 md:pt-36 pt-28">
        {/* Hero */}
        <div className="text-center space-y-4">
          <h1 className="text-4xl md:text-6xl font-bold tracking-tight text-slate-900">
            About <span className="text-primary">Waypoint</span>
          </h1>
          <p className="text-lg text-slate-600 max-w-2xl mx-auto leading-relaxed">
            We are redefining how the world plans, manages, and experiences travel by combining advanced AI engineering with robust tourism operations tools.
          </p>
        </div>

        {/* Vision & Values */}
        <div className="grid gap-6 md:grid-cols-3">
          <Card className="glass-card border border-slate-200">
            <CardContent className="p-6 text-center space-y-3">
              <div className="h-10 w-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center mx-auto">
                <Sparkles className="h-5 w-5" />
              </div>
              <h3 className="font-bold text-lg text-slate-900">AI Planning</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Empowering travelers with personalized itineraries generated by Google Gemini AI in seconds.
              </p>
            </CardContent>
          </Card>
          <Card className="glass-card border border-slate-200">
            <CardContent className="p-6 text-center space-y-3">
              <div className="h-10 w-10 rounded-xl bg-secondary/10 text-secondary flex items-center justify-center mx-auto">
                <Users className="h-5 w-5" />
              </div>
              <h3 className="font-bold text-lg text-slate-900">Shared Platform</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Connecting independent travelers directly with verified regional agencies for authentic local tours.
              </p>
            </CardContent>
          </Card>
          <Card className="glass-card border border-slate-200">
            <CardContent className="p-6 text-center space-y-3">
              <div className="h-10 w-10 rounded-xl bg-secondary/10 text-secondary flex items-center justify-center mx-auto">
                <Shield className="h-5 w-5" />
              </div>
              <h3 className="font-bold text-lg text-slate-900">Trusted Network</h3>
              <p className="text-xs text-slate-600 leading-relaxed">
                Ensuring secure payment transactions via Stripe and Razorpay, backed by full booking confirmation tracking.
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Our Story */}
        <div className="bg-white rounded-2xl border border-slate-200 p-8 space-y-4 shadow-sm">
          <h2 className="text-2xl font-bold text-slate-900">Our Story</h2>
          <p className="text-sm text-slate-600 leading-relaxed">
            Waypoint was founded in 2026 by a group of travel enthusiasts and software engineers who were tired of spending hours browsing scattered travel forums, spreadsheets, and unverified operator websites to coordinate a single holiday.
          </p>
          <p className="text-sm text-slate-600 leading-relaxed">
            We built a centralized platform that bridges the gap between smart AI planning and practical booking logistics. Today, Waypoint serves thousands of traveler accounts and helps dozens of verified local travel agencies automate package creations, vendor accounts, and booking transactions under a single, modern dashboard.
          </p>
        </div>
      </main>

      <SiteFooter />
    </div>
  );
}
