"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";
import {
  Sparkles,
  MapPin,
  Shield,
  Star,
  ArrowRight,
  Plane,
  Clock,
  Users,
  Globe,
  Zap,
  Heart,
  Building2,
  CreditCard,
  Compass,
  ChevronRight,
  ChevronDown,
  CheckCircle2,
  Calendar,
  Utensils,
  Map,
  BadgePercent,
  TrendingUp,
  Flame,
  HelpCircle,
  Check,
  Send,
  Mail,
  Lock,
} from "lucide-react";
import { Swiper, SwiperSlide } from "swiper/react";
import { Autoplay, Pagination } from "swiper/modules";

// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";

// Top Trending Indian Destinations
const DESTINATIONS = [
  {
    id: "manali",
    title: "Solang Valley & Manali",
    state: "Himachal Pradesh",
    packageSlug: "himalayan-adventure-trek",
    image: "/images/packages/himalayan-adventure.jpg",
    duration: "5 Days / 4 Nights",
    rating: 4.9,
    reviews: 142,
    startingPrice: 14999,
    tag: "Adventure • Snow",
    badgeColor: "bg-primary",
    prompt: "Plan a 5-day adventure trip to Manali with Solang Valley paragliding and Beas river trekking",
  },
  {
    id: "kerala",
    title: "Munnar & Alleppey",
    state: "Kerala",
    packageSlug: "kerala-backwaters-bliss",
    image: "/images/packages/kerala-backwaters.jpg",
    duration: "6 Days / 5 Nights",
    rating: 4.95,
    reviews: 218,
    startingPrice: 18500,
    tag: "Relaxing • Nature",
    badgeColor: "bg-secondary",
    prompt: "Plan a 6-day relaxing trip to Kerala backwaters with luxury houseboat and Munnar tea gardens",
  },
  {
    id: "rajasthan",
    title: "Jaipur & Udaipur",
    state: "Rajasthan",
    packageSlug: "rajasthan-royal-heritage",
    image: "/images/packages/rajasthan-heritage.jpg",
    duration: "5 Days / 4 Nights",
    rating: 4.88,
    reviews: 189,
    startingPrice: 16200,
    tag: "Royal • Heritage",
    badgeColor: "bg-secondary",
    prompt: "Plan a 5-day royal heritage tour of Jaipur fort, Amer palace, and Udaipur lake cruise",
  },
  {
    id: "goa",
    title: "North & South Beaches",
    state: "Goa",
    packageSlug: "goa-beach-paradise",
    image: "/images/packages/goa-beach.jpg",
    duration: "4 Days / 3 Nights",
    rating: 4.85,
    reviews: 310,
    startingPrice: 12499,
    tag: "Beaches • Nightlife",
    badgeColor: "bg-[#E8AA9B]",
    prompt: "Plan a 4-day beach getaway to Goa with water sports, beach shacks, and Old Goa churches",
  },
];

// Interactive FAQs
const FAQS = [
  {
    question: "How does the AI Trip Builder generate custom itineraries?",
    answer:
      "Our AI Trip Builder uses Google Gemini AI trained on real regional travel data, verified travel guides, and live operator routes. It converts your natural language prompt into an itemized day-by-day itinerary complete with activities, transportation options, meal stops, and hotel suggestions.",
  },
  {
    question: "Can I customize the generated AI itineraries?",
    answer:
      "Yes! Every draft generated by Gemini can be saved to your personal dashboard, customized with your preferred travel dates, hotel categories, budget adjustments, or exported to share with travel companions.",
  },
  {
    question: "Are the travel agencies and packages on Waypoint verified?",
    answer:
      "All tour packages listed on Waypoint are published by verified travel agencies in India. Each agency undergoes company verification, business document review, and rate validation before listing packages.",
  },
  {
    question: "What payment options and currencies are supported?",
    answer:
      "We integrate directly with Razorpay to offer 100% secure checkouts via UPI, Credit/Debit cards, NetBanking, and wallets. We support multi-currency conversion tracking in INR, USD, EUR, and GBP.",
  },
  {
    question: "How do travel agencies benefit from joining Waypoint?",
    answer:
      "Agencies receive a dedicated operations portal to publish curated package listings, manage staff roles (Manager, Agent, Support), assign operational tasks, and automatically receive traveler bookings with instant invoice generation.",
  },
];

interface LandingClientProps {
  userSession: any;
}

// Real detailed sample itineraries planned by Gemini
const SAMPLE_ITINERARIES = [
  {
    id: "adventure",
    tabTitle: "Manali Adventure",
    tag: "High Energy • Trekking",
    title: "5-Day Solang Valley & Beas Kund Trek",
    summary: "High-altitude hiking, paragliding, and cozy riverside wooden cabin lodging.",
    days: [
      {
        day: "Day 1",
        activity: "Acclimatization & Solang Paragliding",
        desc: "Arrive in Manali, settle into Riverview Cabins, and take a tandem paragliding flight over Solang Valley.",
        icon: Plane,
      },
      {
        day: "Day 2",
        activity: "Dhundi Base Camp Hike",
        desc: "Trek through lush green pine forests and wildflower meadows along the Beas River to Dhundi camp.",
        icon: Map,
      },
      {
        day: "Day 3",
        activity: "Beas Kund Summit & Glacier Walk",
        desc: "Hike up to the holy Beas Kund lake at 12,000ft. Take in stunning views of Hanuman Tibba and Friendship Peak.",
        icon: Compass,
      },
      {
        day: "Day 4",
        activity: "Riverside Bonfire & Local Trout Dining",
        desc: "Return to Manali. Spend the evening visiting Old Manali cafes, dining on wood-fired trout, and gathering around a bonfire.",
        icon: Utensils,
      },
      {
        day: "Day 5",
        activity: "Jogini Waterfall Hike & Departure",
        desc: "A morning walk to Jogini Falls followed by a soak in the Vashisht hot springs before catching the evening bus.",
        icon: Calendar,
      },
    ],
  },
  {
    id: "heritage",
    tabTitle: "Rajasthan Heritage",
    tag: "Cultural • Luxury Stay",
    title: "6-Day Jaipur & Udaipur Palaces",
    summary: "Royal fort exploration, traditional puppet shows, and heritage lake palace stays.",
    days: [
      {
        day: "Day 1",
        activity: "Jaipur Pink City Walking Tour",
        desc: "Explore Hawa Mahal and the astronomical observatory Jantar Mantar with a royal historian guide.",
        icon: Map,
      },
      {
        day: "Day 2",
        activity: "Amer Fort Ride & Traditional Buffet",
        desc: "Ascend to the hilltop Amer Palace. Enjoy a Rajasthani thali dinner complete with live folk performances.",
        icon: Utensils,
      },
      {
        day: "Day 3",
        activity: "Udaipur Transfer & Lake Pichola Cruise",
        desc: "Drive to Udaipur. Board a scenic sunset boat cruise on Lake Pichola passing the Floating Palace.",
        icon: Plane,
      },
      {
        day: "Day 4",
        activity: "City Palace & Vintage Car Museum",
        desc: "Visit the massive City Palace complex followed by high tea at the vintage car pavilion.",
        icon: Compass,
      },
      {
        day: "Day 5",
        activity: "Sajjangarh Monsoon Palace Sunset",
        desc: "Climb up to Sajjangarh Palace for panoramic sunset views over Udaipur’s beautiful lakes.",
        icon: Calendar,
      },
    ],
  },
  {
    id: "tropical",
    tabTitle: "Kerala Serenity",
    tag: "Relaxing • Ayurveda",
    title: "5-Day Alleppey Backwaters & Munnar Tea Estates",
    summary: "Private houseboat cruising, organic spice plantation tours, and tea valley walks.",
    days: [
      {
        day: "Day 1",
        activity: "Private Houseboat Embarkation",
        desc: "Board a traditional Kettuvallam houseboat in Alleppey. Cruise through palm-fringed canals.",
        icon: Plane,
      },
      {
        day: "Day 2",
        activity: "Ayurvedic Massage & Village Walk",
        desc: "Receive a professional full-body abhyanga massage. Take a evening walk along rural paddy fields.",
        icon: Compass,
      },
      {
        day: "Day 3",
        activity: "Munnar Scenic Drive & Tea Factory Visit",
        desc: "Travel uphill through winding roads to Munnar. Visit a colonial tea factory and taste organic green tea.",
        icon: Map,
      },
      {
        day: "Day 4",
        activity: "Anamudi Peak Trek & Spice Garden Tour",
        desc: "A morning walk in Eravikulam National Park to spot Nilgiri Tahr, followed by an organic cardamom plantation tour.",
        icon: Calendar,
      },
      {
        day: "Day 5",
        activity: "Kathakali Art Show & Departure",
        desc: "Witness a traditional Kathakali makeup session and performance in Munnar before checking out.",
        icon: Utensils,
      },
    ],
  },
];

const FEATURES = [
  {
    icon: Sparkles,
    title: "AI Trip Builder",
    description:
      "Describe your dream trip in natural language and receive an absolute custom day-by-day itinerary structured in seconds.",
    colorClass: "text-primary",
    bgClass: "bg-primary/10",
  },
  {
    icon: MapPin,
    title: "Curated Packages",
    description:
      "Browse and book verified tour packages created by expert travel agencies. Easily customize templates to match your dates.",
    colorClass: "text-secondary",
    bgClass: "bg-secondary/10",
  },
  {
    icon: Shield,
    title: "Secure Booking System",
    description:
      "Integrated Razorpay checkout offers complete payment security, instant invoice PDFs, and automatic itinerary links.",
    colorClass: "text-primary",
    bgClass: "bg-primary/10",
  },
  {
    icon: Globe,
    title: "Multi-Currency Engine",
    description:
      "Track prices in INR, USD, EUR, and GBP with real-time automatic conversions. Perfect for agencies catering to international tourists.",
    colorClass: "text-secondary",
    bgClass: "bg-secondary/10",
  },
  {
    icon: Building2,
    title: "Agency Operations Panel",
    description:
      "Manage staff, delegate tasks to managers, keep track of package bookings, and run agency billing workflows.",
    colorClass: "text-primary",
    bgClass: "bg-primary/10",
  },
  {
    icon: TrendingUp,
    title: "Analytics Dashboard",
    description:
      "Visualize revenue trends, active packages, booking rates, and staff completion metrics in a modern dashboard.",
    colorClass: "text-secondary",
    bgClass: "bg-secondary/10",
  },
];

const STATS = [
  { value: "500+", label: "Destinations", icon: MapPin },
  { value: "50+", label: "Agencies Onboard", icon: Building2 },
  { value: "10K+", label: "Itineraries Created", icon: Compass },
  { value: "4.9", label: "Client Rating", icon: Star },
];

const TESTIMONIALS = [
  {
    name: "Priya Mehta",
    role: "Solo Traveler",
    destination: "Rajasthan",
    text: "Waypoint's AI planned my entire Rajasthan trip in 30 seconds. The itinerary was spot-on — every restaurant, every timing. Incredible!",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop",
  },
  {
    name: "Arjun Kapoor",
    role: "Travel Blogger",
    destination: "Manali",
    text: "As someone who's traveled 40+ countries, I'm impressed by how accurate and detailed the AI suggestions are. This is the future of travel.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop",
  },
  {
    name: "Meera Nair",
    role: "Travel Agency Owner",
    destination: "Kerala",
    text: "We onboarded our agency on Waypoint and saw a 3x increase in bookings within the first month. The platform is a game-changer.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop",
  },
  {
    name: "Dr. Rohan Shah",
    role: "Family Traveler",
    destination: "Munnar",
    text: "Planning family trips used to be stressful. Waypoint organized dates, custom dietary dining stops, and secure ticket passes beautifully.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop",
  },
  {
    name: "Aditi Rao",
    role: "Backpacker",
    destination: "Meghalaya",
    text: "The budget converter features and live rates are extremely helpful. Did an entire North-East India budget tour using Waypoint's draft.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop",
  },
  {
    name: "Vikram Sherpa",
    role: "Adventure Tour Operator",
    destination: "Solang Valley",
    text: "Managing tasks, package listings, and payments in one dashboard has streamlined our business operations. Highly recommended for operators.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop",
  },
];

const FOOTER_LINKS = {
  Product: [
    { label: "Browse Packages", href: "/packages" },
    { label: "AI Trip Builder", href: "/trip-builder" },
    { label: "For Agencies", href: "/register" },
  ],
  Company: [
    { label: "About Us", href: "/about" },
    { label: "Contact", href: "/contact" },
    { label: "Privacy Policy", href: "/privacy" },
  ],
  Support: [
    { label: "Help Center", href: "/contact" },
    { label: "Terms of Service", href: "/terms" },
    { label: "API Docs", href: "/about" },
  ],
};

export default function LandingClient({ userSession }: LandingClientProps) {
  const router = useRouter();
  const [activeItineraryTab, setActiveItineraryTab] = useState("adventure");
  const [customPrompt, setCustomPrompt] = useState("");
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const currentItinerary = SAMPLE_ITINERARIES.find(
    (item) => item.id === activeItineraryTab
  )!;



  const handlePromptSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (customPrompt.trim()) {
      router.push(`/trip-builder?prompt=${encodeURIComponent(customPrompt.trim())}`);
    } else {
      router.push("/trip-builder");
    }
  };

  const handlePillClick = (promptText: string) => {
    router.push(`/trip-builder?prompt=${encodeURIComponent(promptText)}`);
  };

  return (
    <div className="flex flex-col min-h-screen bg-[#FAFAF9] text-slate-900 font-sans">
      {/* ═══════════════ FLOATING PILL NAVBAR ═══════════════ */}
      <SiteHeader userSession={userSession} />

      {/* ═══════════════ HERO SECTION — Centered Content + Preview Below ═══════════════ */}
      <section className="hero-sec relative md:pt-36 sm:pt-32 pt-28 lg:pb-16 pb-10 lg:pt-40 overflow-hidden bg-gradient-to-b from-[#FDF8F5] via-[#FAF7F4] to-[#FAFAF9]">

        {/* ── Premium Background Layers ── */}

        {/* Warm ambient glow — top-left */}
        <div className="absolute -top-32 -left-40 w-[600px] h-[600px] bg-gradient-to-br from-primary/[0.08] via-[#E8AA9B]/[0.06] to-transparent rounded-full blur-[120px] pointer-events-none" />

        {/* Cool ambient glow — top-right */}
        <div className="absolute -top-20 -right-32 w-[500px] h-[500px] bg-gradient-to-bl from-secondary/[0.06] via-[#769ABC]/[0.04] to-transparent rounded-full blur-[140px] pointer-events-none" />

        {/* Center soft spotlight */}
        <div className="absolute top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[500px] rounded-full blur-[100px] pointer-events-none" style={{ background: 'radial-gradient(ellipse at center, rgba(228,111,68,0.03), transparent 70%)' }} />

        {/* Bottom fade-out glow */}
        <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-[900px] h-[300px] bg-gradient-to-t from-[#FAFAF9] via-[#FAFAF9]/80 to-transparent pointer-events-none z-[1]" />

        {/* Subtle grid pattern overlay */}
        <div className="absolute inset-0 opacity-[0.03] pointer-events-none" style={{ backgroundImage: 'linear-gradient(rgba(26,59,90,0.3) 1px, transparent 1px), linear-gradient(90deg, rgba(26,59,90,0.3) 1px, transparent 1px)', backgroundSize: '60px 60px' }} />

        {/* Decorative geometric accent rings */}
        <div className="absolute top-24 right-[12%] w-48 h-48 rounded-full border border-primary/[0.07] pointer-events-none hidden lg:block" />
        <div className="absolute top-32 right-[14%] w-32 h-32 rounded-full border border-dashed border-secondary/[0.06] pointer-events-none hidden lg:block" />
        <div className="absolute bottom-40 left-[8%] w-40 h-40 rounded-full border border-[#E8AA9B]/[0.08] pointer-events-none hidden lg:block" />
        <div className="absolute bottom-52 left-[10%] w-24 h-24 rounded-full border border-dashed border-primary/[0.05] pointer-events-none hidden lg:block" />

        {/* Floating dot accents */}
        <div className="absolute top-44 left-[18%] w-2 h-2 rounded-full bg-primary/[0.12] pointer-events-none hidden lg:block" />
        <div className="absolute top-60 right-[20%] w-1.5 h-1.5 rounded-full bg-secondary/[0.15] pointer-events-none hidden lg:block" />
        <div className="absolute bottom-60 right-[15%] w-2.5 h-2.5 rounded-full bg-[#E8AA9B]/[0.12] pointer-events-none hidden lg:block" />

        {/* ── CENTERED HERO COPY ── */}
        <div className="container mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 relative z-10 text-center">

          {/* Badge */}
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-primary/10 border border-primary/20 text-[11px] font-bold uppercase tracking-widest text-primary md:mb-7 mb-5">
            <Sparkles className="h-3.5 w-3.5" />
            <span>Powered by Gemini AI</span>
          </div>

          {/* Headline */}
          <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold tracking-tight leading-[1.08] text-slate-900 font-display mb-6">
            The intelligent way to{" "}
            <span className="bg-gradient-to-r from-primary via-[#E8AA9B] to-secondary bg-clip-text text-transparent">
              plan your journey.
            </span>
          </h1>

          {/* Subheadline */}
          <p className="md:text-base text-sm text-slate-500 md:leading-relaxed max-w-3xl mx-auto md:mb-8 mb-6">
            Describe your dream trip in simple words and watch AI build an itemized day-by-day itinerary - or explore verified tour packages from local travel agencies across India.
          </p>

          {/* AI Prompt Input + CTA */}
          <form onSubmit={handlePromptSubmit} className="flex flex-col items-center gap-4 mb-8">
            <div className="relative w-full max-w-2xl flex items-center bg-white border border-slate-200 rounded-xl shadow-md focus-within:border-primary focus-within:ring-4 focus-within:ring-primary/10 transition-all">
              <Sparkles className="sm:block hidden absolute left-4 h-5 w-5 text-primary pointer-events-none shrink-0" />
              <Input
                value={customPrompt}
                onChange={(e) => setCustomPrompt(e.target.value)}
                placeholder="Where do you want to go? e.g. 5-day Manali snow trek..."
                className="flex-1 sm:ps-12 ps-4 sm:pe-36 pe-32 sm:h-14 h-12 text-sm rounded-2xl bg-transparent border-0 text-slate-900 placeholder:text-slate-400 focus-visible:ring-0 focus-visible:ring-offset-0"
              />
              <Button
                type="submit"
                variant="default"
                className="absolute sm:right-2 right-1 font-bold text-sm bg-primary hover:bg-primary/90 text-white cursor-pointer shadow-sm transition-all"
              >
                Generate <ArrowRight className="h-3.5 w-3.5" />
              </Button>
            </div>

            {/* Quick prompt pills */}
            <div className="flex flex-wrap justify-center items-center gap-2">
              <span className="text-[11px] font-semibold text-slate-400">Try:</span>
              {[
                { label: "🏔️ Manali Solang Trek", prompt: "Plan a 5-day adventure trek to Solang Valley Manali with paragliding and riverside cabin stay" },
                { label: "🌴 Kerala Backwaters", prompt: "Plan a 6-day relaxing trip to Kerala backwaters with luxury houseboat and Munnar tea estates" },
                { label: "🏰 Rajasthan Forts", prompt: "Plan a 5-day royal heritage tour of Jaipur and Udaipur with lake cruise and palace stays" },
                { label: "🏖️ Goa Beach Getaway", prompt: "Plan a 4-day beach trip to Goa with water sports, beach shacks, and Old Goa sightseeing" },
              ].map((pill) => (
                <button
                  key={pill.label}
                  type="button"
                  onClick={() => handlePillClick(pill.prompt)}
                  className="px-3 py-1.5 rounded-full bg-white border border-slate-200/80 text-[11px] font-medium text-slate-600 hover:border-primary hover:text-primary transition-all cursor-pointer shadow-sm"
                >
                  {pill.label}
                </button>
              ))}
            </div>
          </form>

          {/* Social Proof Row */}
          <div className="flex sm:flex-row sm:text-start text-center flex-col items-center justify-center gap-5 gap-y-4 mb-8">
            <div className="flex -space-x-2.5 overflow-hidden">
              <img src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=120&auto=format&fit=crop" alt="Priya Mehta" className="inline-block h-9 w-9 rounded-full object-cover ring-2 ring-white shadow-sm" />
              <img src="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=120&auto=format&fit=crop" alt="Arjun Kapoor" className="inline-block h-9 w-9 rounded-full object-cover ring-2 ring-white shadow-sm" />
              <img src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=120&auto=format&fit=crop" alt="Dr. Rohan Shah" className="inline-block h-9 w-9 rounded-full object-cover ring-2 ring-white shadow-sm" />
              <img src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=120&auto=format&fit=crop" alt="Aditi Rao" className="inline-block h-9 w-9 rounded-full object-cover ring-2 ring-white shadow-sm" />
              <img src="https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=120&auto=format&fit=crop" alt="Meera Nair" className="inline-block h-9 w-9 rounded-full object-cover ring-2 ring-white shadow-sm" />
            </div>
            <div className="text-left">
              <div className="flex items-center sm:justify-start justify-center mb-1 gap-1 text-primary">
                {Array.from({ length: 5 }).map((_, i) => (
                  <Star key={i} className="h-3.5 w-3.5 fill-current" />
                ))}
                <span className="font-bold text-slate-800 ml-1 text-sm">4.9/5</span>
              </div>
              <p className="text-[11px] text-slate-400 font-medium">Trusted by 10,000+ travelers across India</p>
            </div>
          </div>
        </div>

        {/* ── FULL-WIDTH APP PREVIEW BELOW CONTENT ── */}
        <div className="relative z-10 container mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">

          {/* Browser-frame mockup — actual Waypoint dashboard */}
          <div className="w-full bg-white border border-slate-200/80 rounded-2xl shadow-md overflow-hidden">

            {/* Browser chrome */}
            <div className="bg-slate-50 px-4 py-2.5 border-b border-slate-200/60 flex items-center gap-3">
              <div className="flex items-center gap-1.5 shrink-0">
                <span className="h-2.5 w-2.5 rounded-full bg-red-400" />
                <span className="h-2.5 w-2.5 rounded-full bg-yellow-400" />
                <span className="h-2.5 w-2.5 rounded-full bg-green-400" />
              </div>
              <div className="flex-1 min-w-0 bg-white border border-slate-200 rounded px-3 py-1 text-[10px] text-slate-500 font-medium mx-2 overflow-hidden whitespace-nowrap text-ellipsis">
                waypoint.app/dashboard
              </div>
              <div className="text-[8px] px-2 py-0.5 rounded-full bg-green-100 text-green-700 font-bold shrink-0">● LIVE</div>
            </div>

            {/* Dashboard layout */}
            <div className="flex">

              {/* ── SIDEBAR ── */}
              <div className="hidden lg:flex flex-col w-44 shrink-0 border-r border-slate-100 bg-white relative">
                {/* Logo */}
                <div className="flex items-center gap-2 px-4 py-3 border-b border-slate-100">
                  <img
                    src="/images/logo-dark.png"
                    alt="Waypoint"
                    className="h-6 w-auto object-contain"
                  />
                </div>

                {/* Nav items */}
                <nav className="flex-1 py-2 space-y-2">
                  {[
                    { icon: Globe, label: "Dashboard", active: true },
                    { icon: Map, label: "My Trips", active: false },
                    { icon: Calendar, label: "Bookings", active: false },
                    { icon: Heart, label: "Favorites", active: false },
                    { icon: Sparkles, label: "AI Trip Builder", active: false },
                    { icon: Users, label: "Profile", active: false },
                  ].map(({ icon: Icon, label, active }) => (
                    <div
                      key={label}
                      className={`flex items-center gap-2.5 px-4 py-2 text-[12px] font-semibold transition-colors ${active
                        ? "bg-primary/8 text-primary border-r-2 border-primary"
                        : "text-slate-500"
                        }`}
                    >
                      <Icon className="h-3 w-3 shrink-0" />
                      {label}
                    </div>
                  ))}
                </nav>

                {/* Bottom user profile */}
                <div className="border-t border-slate-100 px-4 py-3">
                  <div className="flex items-center gap-2 mb-1.5">
                    <img
                      src="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=60&auto=format&fit=crop"
                      alt="Rohit Sharma"
                      className="w-6 h-6 rounded-full object-cover ring-1 ring-slate-200 shrink-0"
                    />
                    <div className="min-w-0">
                      <div className="text-[9px] font-bold text-slate-800 truncate">Rohit Sharma</div>
                      <div className="text-[8px] text-slate-400 uppercase tracking-wider">Traveler</div>
                    </div>
                  </div>
                  <div className="text-[9px] text-slate-400 hover:text-slate-600 cursor-pointer">Log out</div>
                </div>
              </div>

              {/* ── MAIN CONTENT ── */}
              <div className="flex-1 min-w-0 bg-slate-50/50 flex flex-col">

                {/* Top search bar */}
                <div className="bg-white border-b border-slate-100 px-4 py-2.5 flex items-center justify-between gap-3">
                  <div className="flex-1 flex items-center gap-2 bg-slate-50 border border-slate-200 rounded-lg px-2.5 py-1.5 max-w-xs">
                    <Globe className="h-3 w-3 text-slate-400 shrink-0" />
                    <span className="text-[10px] text-slate-400">Search packages...</span>
                    <div className="ml-auto bg-secondary text-white text-[9px] font-bold px-2 py-0.5 rounded">Search</div>
                  </div>
                  <div className="relative">
                    <div className="w-6 h-6 rounded-full bg-slate-100 flex items-center justify-center">
                      <Globe className="h-3 w-3 text-slate-500" />
                    </div>
                    <span className="absolute -top-1 -right-1 w-3.5 h-3.5 rounded-full bg-primary text-[7px] text-white font-bold flex items-center justify-center">2</span>
                  </div>
                </div>

                {/* Page content */}
                <div className="flex-1 p-4 md:space-y-4 overflow-hidden">

                  {/* Welcome header */}
                  <div>
                    <div className="flex items-center gap-1.5">
                      <span className="text-lg font-bold text-slate-900">Welcome back, Rohit 👋</span>
                    </div>
                    <p className="text-sm text-slate-500 mt-0.5">Here's what's happening with your travels.</p>
                  </div>

                  {/* 4 Stat Cards */}
                  <div className="grid grid-cols-2 md:grid-cols-4 sm:gap-4 gap-3 sm:mt-0 mt-4">
                    {[
                      { label: "AI Trips", value: "1", sub: "Generated plans", icon: Sparkles, color: "#E46F44" },
                      { label: "Active Bookings", value: "9", sub: "Total bookings", icon: Calendar, color: "#769ABC" },
                      { label: "Saved Packages", value: "2", sub: "Browse packages", icon: Heart, color: "#E8AA9B" },
                      { label: "Destinations", value: "∞", sub: "To explore", icon: Globe, color: "#1A3B5A" },
                    ].map(({ label, value, sub, icon: Icon, color }) => (
                      <div key={label} className="bg-white border border-slate-200/80 rounded-xl p-3 shadow-sm">
                        <div className="flex items-center justify-between mb-2">
                          <span className="text-[11px] font-semibold text-slate-500">{label}</span>
                          <Icon className="h-3 w-3" style={{ color }} />
                        </div>
                        <div className="text-2xl font-bold text-slate-900 leading-none">{value}</div>
                        <div className="text-[10px] text-slate-400 mt-1">{sub}</div>
                      </div>
                    ))}
                  </div>

                  {/* 2 Quick Action Cards */}
                  <div className="md:grid hidden grid-cols-1 sm:grid-cols-2 gap-4">
                    <div className="bg-white border border-slate-200/80 rounded-xl p-3 py-5 shadow-sm flex items-center justify-between group cursor-pointer hover:border-primary/40 transition-colors">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-xl bg-secondary/15 flex items-center justify-center shrink-0">
                          <Sparkles className="h-4 w-4 text-secondary" />
                        </div>
                        <div>
                          <div className="text-[14px] font-bold text-slate-900 mb-1">AI Trip Builder</div>
                          <div className="text-[11px] text-slate-400">Create a personalized trip with AI</div>
                        </div>
                      </div>
                      <ArrowRight className="h-3.5 w-3.5 text-slate-400 shrink-0" />
                    </div>
                    <div className="bg-white border border-slate-200/80 rounded-xl p-3 py-5 shadow-sm flex items-center justify-between group cursor-pointer hover:border-primary/40 transition-colors">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-xl bg-primary/15 flex items-center justify-center shrink-0">
                          <MapPin className="h-4 w-4 text-primary" />
                        </div>
                        <div>
                          <div className="text-[14px] font-bold text-slate-900 mb-1">Browse Packages</div>
                          <div className="text-[11px] text-slate-400">Explore curated travel packages</div>
                        </div>
                      </div>
                      <ArrowRight className="h-3.5 w-3.5 text-slate-400 shrink-0" />
                    </div>
                  </div>

                  {/* Charts Row */}
                  <div className="md:grid hidden grid-cols-1 sm:grid-cols-2 gap-4">

                    {/* Monthly Spending Bar Chart */}
                    <div className="bg-white border border-slate-200/80 rounded-xl p-3 shadow-sm">
                      <div className="flex items-center gap-1.5 mb-3">
                        <TrendingUp className="h-3 w-3 text-slate-500" />
                        <span className="text-xs font-bold text-slate-900">Monthly Spending</span>
                      </div>
                      {/* Y-axis labels + bars */}
                      <div className="flex gap-1 items-end h-[120px] relative">
                        {/* Y-axis */}
                        <div className="flex flex-col justify-between h-full text-right pr-1.5 shrink-0">
                          {["₹600k", "₹450k", "₹300k", "₹150k", "₹0"].map(l => (
                            <span key={l} className="text-[8px] text-slate-400 leading-none">{l}</span>
                          ))}
                        </div>
                        {/* Gridlines + Bars */}
                        <div className="flex-1 relative flex items-end gap-1.5 border-b border-l border-slate-100 pl-1">
                          {[
                            { month: "Mar", h: "15%" },
                            { month: "Apr", h: "10%" },
                            { month: "May", h: "20%" },
                            { month: "Jun", h: "80%" },
                            { month: "Jul", h: "5%" },
                            { month: "Aug", h: "5%" },
                          ].map(({ month, h }) => (
                            <div key={month} className="flex flex-col items-center gap-1 flex-1">
                              <div
                                className="w-full rounded-t-sm"
                                style={{
                                  height: h,
                                  background: month === "Jun"
                                    ? "linear-gradient(to top, #1A3B5A, #769ABC)"
                                    : "#e2e8f0",
                                  minHeight: 3,
                                }}
                              />
                              <span className="text-[8px] text-slate-400">{month}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>

                    {/* Bookings by Status — Donut chart (pure CSS) */}
                    <div className="bg-white border border-slate-200/80 rounded-xl p-3 shadow-sm">
                      <div className="flex items-center gap-1.5 mb-3">
                        <Clock className="h-3 w-3 text-slate-500" />
                        <span className="text-xs font-bold text-slate-900">Bookings by Status</span>
                      </div>
                      <div className="flex items-center justify-between gap-3">
                        {/* SVG Donut */}
                        <div className="shrink-0">
                          <svg width="120" height="120" viewBox="0 0 80 80">
                            {/* Background circle */}
                            <circle cx="40" cy="40" r="28" fill="none" stroke="#f1f5f9" strokeWidth="12" />
                            {/* Cancelled — orange 35% of 175.9 = 61.6 */}
                            <circle cx="40" cy="40" r="28" fill="none" stroke="#f59e0b" strokeWidth="12"
                              strokeDasharray="61.6 114.3" strokeDashoffset="0" strokeLinecap="butt"
                              transform="rotate(-90 40 40)" />
                            {/* Completed — purple 30% = 52.8 */}
                            <circle cx="40" cy="40" r="28" fill="none" stroke="#8b5cf6" strokeWidth="12"
                              strokeDasharray="52.8 123.1" strokeDashoffset="-61.6" strokeLinecap="butt"
                              transform="rotate(-90 40 40)" />
                            {/* Confirmed — blue 35% = 61.6 */}
                            <circle cx="40" cy="40" r="28" fill="none" stroke="#38bdf8" strokeWidth="12"
                              strokeDasharray="61.5 114.4" strokeDashoffset="-114.4" strokeLinecap="butt"
                              transform="rotate(-90 40 40)" />
                          </svg>
                        </div>
                        {/* Legend */}
                        <div className="flex flex-col gap-1.5 text-[12px]">
                          <div className="flex items-center gap-1.5">
                            <span className="w-2.5 h-2.5 rounded-sm bg-amber-400 shrink-0" />
                            <span className="text-slate-600">Cancelled</span>
                          </div>
                          <div className="flex items-center gap-1.5">
                            <span className="w-2.5 h-2.5 rounded-sm bg-violet-500 shrink-0" />
                            <span className="text-slate-600">Completed</span>
                          </div>
                          <div className="flex items-center gap-1.5">
                            <span className="w-2.5 h-2.5 rounded-sm bg-sky-400 shrink-0" />
                            <span className="text-slate-600">Confirmed</span>
                          </div>
                        </div>
                      </div>
                    </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ═══════════════ STATS ROW ═══════════════ */}
      <section className="stats-sec py-10 lg:py16 bg-white border-y border-slate-200/50">
        <div className="container mx-auto px-4 max-w-7xl">
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-5 lg:gap-0">
            {STATS.map((stat, index) => (
              <div
                key={stat.label}
                className="flex items-center md:justify-center gap-5 group transition-all duration-300 relative"
              >
                {/* Visual Icon Accent */}
                <div className="md:h-12 md:w-12 h-10 w-10 md:rounded-2xl rounded-lg bg-primary/10 flex items-center justify-center shrink-0 group-hover:scale-110 group-hover:bg-primary group-hover:text-white transition-all duration-300 text-primary">
                  <stat.icon className="md:h-5.5 md:w-5.5 h-4 w-4 transition-colors duration-300" />
                </div>
                <div className="md:space-y-2 space-y-1">
                  <h4 className="md:text-3xl text-2xl font-bold tracking-tight text-slate-900 font-display">
                    {stat.value}
                  </h4>
                  <p className="text-[11px] text-slate-400 font-bold uppercase tracking-widest">
                    {stat.label}
                  </p>
                </div>

                {/* Vertical Divider for Desktop */}
                {index < STATS.length - 1 && (
                  <div className="hidden lg:block absolute right-0 top-1/2 -translate-y-1/2 w-[1px] h-10 bg-slate-200/80" />
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ═══════════════ TOP TRENDING DESTINATIONS SHOWCASE ═══════════════ */}
      <section id="destinations" className="destinations-sec py-10 lg:py-16 bg-[#FAFAF9] scroll-mt-16">
        <div className="container mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col md:flex-row md:items-end items-center justify-between lg:mb-12 mb-8 gap-6 ">
            <div className="md:text-start text-center space-y-4">
              <div className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-full bg-primary/10 text-primary text-[10px] font-bold uppercase tracking-widest border border-primary/20">
                <Flame className="h-3.5 w-3.5" /> Trending Routes
              </div>
              <h2 className="text-2xl sm:text-3xl md:text-5xl font-bold font-display text-slate-900">
                Explore Popular <span className="text-primary">Indian Destinations</span>
              </h2>
              <p className="text-slate-500 lg:text-base text-sm max-w-lg lg:leading-relaxed">
                Hand-crafted itinerary templates and agency packages tailored for adventure, relaxation, and royal culture.
              </p>
            </div>
            <Link href="/packages" className="inline-flex">
              <Button variant="outline" className="h-11 px-6 text-sm font-bold gap-2 cursor-pointer border-slate-200/80 hover:border-primary transition-all">
                Browse All Packages <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {DESTINATIONS.map((item) => (
              <div
                key={item.id}
                onClick={() => router.push(`/packages/${item.packageSlug}`)}
                className="group relative rounded-xl overflow-hidden bg-white border border-slate-200/80 shadow-sm hover:shadow-xl hover:border-primary transition-all duration-300 hover:-translate-y-1.5 flex flex-col justify-between cursor-pointer"
              >
                {/* Visual Image Container with Hover Zoom */}
                <div className="h-52 w-full overflow-hidden relative">
                  <img
                    src={item.image}
                    alt={item.title}
                    className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-slate-950 via-slate-950/50 to-transparent pointer-events-none" />

                  {/* Category Tag Badge */}
                  <span className={`absolute top-3 left-3 px-2.5 py-1 rounded-lg ${item.badgeColor} text-white text-[10px] font-bold uppercase tracking-wider shadow-sm border border-white/10`}>
                    {item.tag}
                  </span>

                  {/* Rating Badge */}
                  <span className="absolute top-3 right-3 px-2 py-1 rounded-lg bg-slate-950/80 backdrop-blur-md text-white text-[10px] font-bold flex items-center gap-1 border border-white/10 shadow-sm">
                    <Star className="h-3 w-3 fill-primary text-primary" /> {item.rating} ({item.reviews})
                  </span>

                  {/* Location Title Overlay */}
                  <div className="absolute bottom-3 left-3 right-3 text-white z-10 space-y-0.5">
                    <span className="text-[10px] font-bold text-[#E8AA9B] uppercase tracking-widest block drop-shadow-sm">
                      {item.state}
                    </span>
                    <h3 className="text-base sm:text-lg font-bold font-display leading-tight text-white drop-shadow-md">
                      {item.title}
                    </h3>
                  </div>
                </div>

                {/* Content Info */}
                <div className="p-4 space-y-3 flex-1 flex flex-col justify-between">
                  <div className="flex items-center justify-between text-xs text-slate-500">
                    <span className="flex items-center gap-1"><Clock className="h-3.5 w-3.5 text-secondary" /> {item.duration}</span>
                    <span className="text-[11px] font-semibold text-slate-400">Verified Agency</span>
                  </div>

                  <div className="pt-3 border-t border-slate-100 flex items-center justify-between gap-2">
                    <div>
                      <span className="text-[10px] text-slate-400 block font-semibold uppercase">From</span>
                      <span className="text-base font-bold text-slate-900 font-display">₹{item.startingPrice.toLocaleString("en-IN")}</span>
                    </div>
                    <div className="flex items-center gap-1.5">
                      <Link
                        href={`/packages/${item.packageSlug}`}
                        onClick={(e) => e.stopPropagation()}
                        className="h-8 px-2.5 rounded-md border border-slate-200 hover:border-primary text-slate-700 hover:text-primary text-[11px] font-bold flex items-center transition-all"
                      >
                        View
                      </Link>
                      <button
                        type="button"
                        onClick={(e) => {
                          e.stopPropagation();
                          handlePillClick(item.prompt);
                        }}
                        className="h-8 px-2.5 rounded-md bg-primary/10 text-primary text-[11px] font-bold flex items-center gap-1 hover:bg-primary hover:text-white transition-all cursor-pointer"
                      >
                        AI Plan <Sparkles className="h-3 w-3" />
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ═══════════════ INTERACTIVE SAMPLE ITINERARY DEMOS ═══════════════ */}
      <section id="itineraries" className="itineraries-sec py-10 lg:py-16 bg-white scroll-mt-16">
        <div className="container mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <div className="text-center lg:mb-10 mb-6 space-y-4">
            <div className="inline-flex items-center gap-1.5 px-3 py-2 rounded-full bg-primary/10 text-primary text-[11px] font-bold uppercase tracking-widest">
              <Sparkles className="h-3.5 w-3.5" /> AI Custom Outputs
            </div>
            <h2 className="text-2xl sm:text-3xl md:text-5xl font-bold font-display">
              See what Gemini AI plans in <span className="text-primary">10 seconds</span>.
            </h2>
            <p className="text-slate-500 lg:text-base text-sm max-w-xl mx-auto lg:leading-relaxed">
              Explore dynamic itineraries built based on traveler tags, local guide feeds, and budget coordinates.
            </p>

            {/* Selector tabs */}
            <div className="flex flex-wrap justify-center gap-3 pt-4">
              {SAMPLE_ITINERARIES.map((item) => (
                <button
                  key={item.id}
                  onClick={() => setActiveItineraryTab(item.id)}
                  className={`sm:px-6 sm:py-2.5 px-4 py-2 rounded-full text-sm font-semibold border transition-all cursor-pointer ${activeItineraryTab === item.id
                    ? "bg-primary text-white border-transparent shadow-md scale-105"
                    : "bg-white text-slate-600 border-slate-200/60 hover:border-primary"
                    }`}
                >
                  {item.tabTitle}
                </button>
              ))}
            </div>
          </div>

          {/* Active Tab Preview Display */}
          <div className="grid grid-cols-1 md:grid-cols-12 lg:gap-8 gap-6 items-start max-w-5xl mx-auto">
            {/* Header info */}
            <div className="lg:col-span-4 md:col-span-5 space-y-5 bg-white sm:p-6 p-4 rounded-2xl border border-slate-200/60 shadow-xs">
              <span className="inline-block px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider bg-secondary/10 text-secondary">
                {currentItinerary.tag}
              </span>
              <h3 className="sm:text-xl text-lg font-bold font-display leading-tight text-slate-900">{currentItinerary.title}</h3>
              <p className="text-sm text-slate-500">{currentItinerary.summary}</p>

              <div className="pt-5 border-t border-slate-100">
                <Link href="/trip-builder" className="w-full flex">
                  <Button variant="default" className="w-full">
                    Plan Similar Trip <Sparkles className="h-3.5 w-3.5" />
                  </Button>
                </Link>
              </div>
            </div>

            {/* Days list preview - Dashed Timeline Flow */}
            <div className="lg:col-span-8 md:col-span-7 relative space-y-6 pl-6 sm:pl-8 border-l-2 border-dashed border-slate-200 lg:ml-6">
              {currentItinerary.days.map((d, index) => (
                <div
                  key={index}
                  className="relative flex flex-col sm:flex-row gap-4 sm:p-5 p-4 bg-white rounded-2xl border border-slate-200/60 shadow-xs hover:shadow-md transition-all duration-300 group"
                >
                  {/* Timeline Pulse Indicator */}
                  <div className="absolute -left-[33px] sm:-left-[41px] top-8 h-4 w-4 rounded-full border-4 border-[#FAFAF9] bg-primary group-hover:scale-125 transition-all shadow-xs" />

                  {/* Icon Card */}
                  <div className="h-10 w-10 rounded-xl bg-primary/5 flex items-center justify-center shrink-0 group-hover:bg-primary/10 transition-colors">
                    <d.icon className="h-5 w-5 text-primary" />
                  </div>

                  <div className="space-y-2 flex-1">
                    <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
                      <span className="text-[10px] font-bold text-primary uppercase tracking-widest">{d.day}</span>
                      <span className="h-1 w-1 rounded-full bg-slate-300 hidden sm:inline-block" />
                      <h4 className="text-lg font-bold text-slate-900 font-display leading-tight">{d.activity}</h4>
                    </div>
                    <p className="text-sm text-slate-500">{d.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ═══════════════ CORE FEATURES ═══════════════ */}
      <section id="features" className="features-sec pb-10 lg:pb-16 bg-white scroll-mt-24">
        <div className="container mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">

          {/* Section Header */}
          <div className="text-center lg:mb-10 mb-6 space-y-4">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-secondary/10 text-secondary text-[11px] font-bold uppercase tracking-widest border border-secondary/20">
              <Zap className="h-3.5 w-3.5" /> Platform Capabilities
            </div>
            <h2 className="text-2xl sm:text-3xl md:text-5xl font-bold font-display">
              Everything you need to{" "}
              <span className="text-primary">travel smarter.</span>
            </h2>
            <p className="text-slate-500 lg:text-base text-sm max-w-xl mx-auto lg:leading-relaxed">
              From AI-generated itineraries to agency dashboards and secure payments — all in one place.
            </p>
          </div>

          {/* Bento Feature Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5 lg:gap-6">
            {FEATURES.map((feat, i) => (
              <div
                key={feat.title}
                className="group relative md:p-7 sm:p-5 p-4 bg-white rounded-2xl border border-slate-200 hover:border-primary/60 shadow-sm hover:shadow-xl transition-all duration-300 hover:-translate-y-1.5 overflow-hidden"
              >
                {/* Number watermark */}
                <span className="absolute top-4 right-5 text-[56px] font-black text-slate-100 select-none leading-none group-hover:text-primary/8 transition-colors duration-300">
                  {String(i + 1).padStart(2, "0")}
                </span>

                {/* Icon */}
                <div className={`relative z-10 h-12 w-12 rounded-xl ${feat.bgClass} flex items-center justify-center mb-5 group-hover:scale-110 transition-transform duration-300`}>
                  <feat.icon className={`h-5.5 w-5.5 ${feat.colorClass}`} />
                </div>

                {/* Content */}
                <div className="relative z-10 space-y-2.5">
                  <h3 className="text-lg font-bold font-display text-slate-900 leading-snug">{feat.title}</h3>
                  <p className="text-sm text-slate-500 lg:leading-relaxed">{feat.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ═══════════════ HOW IT WORKS ═══════════════ */}
      <section id="how-it-works" className="how-it-works-sec py-10 lg:py-16 bg-slate-50 scroll-mt-16">
        <div className="container mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          {/* Header */}
          <div className="text-center lg:mb-10 mb-6 space-y-4">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-primary/10 border border-primary/20 text-[11px] font-bold uppercase tracking-widest text-primary">
              <Zap className="h-3.5 w-3.5" /> How It Works
            </div>
            <h2 className="text-2xl sm:text-3xl md:text-5xl font-bold font-display">
              From idea to itinerary{" "}
              <span className="text-primary">in 3 steps.</span>
            </h2>
            <p className="text-slate-500 lg:text-base text-sm max-w-xl mx-auto lg:leading-relaxed">
              Waypoint's AI engine turns your travel idea into a complete, bookable plan in under a minute.
            </p>
          </div>

          {/* Steps */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 lg:gap-8">
            {[
              {
                step: 1,
                icon: Sparkles,
                title: "Describe your trip",
                desc: "Type your destination, budget, and travel style in plain words. Gemini AI reads your intent and local travel data in real-time.",
                color: "#E46F44",
                bg: "bg-primary/10",
                highlight: "AI Prompt Engine",
                pill: "\"Plan a 5-day trek to Manali with paragliding...\"",
              },
              {
                step: 2,
                icon: Map,
                title: "Get your itinerary",
                desc: "Receive a full day-by-day plan: activities, dining stops, hotel picks, transportation, and estimated costs — all structured.",
                color: "#769ABC",
                bg: "bg-secondary/10",
                highlight: "Day-by-Day Plan",
                pill: "Day 1 → Solang Valley ● Day 2 → Beas Kund Trek",
              },
              {
                step: 3,
                icon: Shield,
                title: "Book & confirm securely",
                desc: "Pay via Razorpay. Get instant PDF invoices, active ticket IDs, and booking confirmations on your dashboard.",
                color: "#E46F44",
                bg: "bg-primary/10",
                highlight: "Secure Checkout",
                pill: "Ticket #WP-4089 ● Razorpay Verified",
              },
            ].map((s, i) => (
              <div key={s.step} className="group relative bg-white rounded-2xl border border-slate-200/70 lg:p-7 sm:p-5 p-4 hover:border-slate-300 hover:shadow-lg shadow-sm transition-all duration-300">

                {/* Step badge */}
                <div className="flex items-center gap-3 mb-5">
                  <div className={`h-10 w-10 rounded-xl ${s.bg} flex items-center justify-center shrink-0 group-hover:scale-110 transition-transform duration-300`}>
                    <s.icon className="h-5 w-5" style={{ color: s.color }} />
                  </div>
                  <span className="text-[11px] font-bold uppercase tracking-widest" style={{ color: s.color }}>Step {String(s.step).padStart(2, '0')}</span>
                </div>

                {/* Text */}
                <h3 className="text-lg font-bold text-slate-900 font-display mb-2.5 leading-snug">{s.title}</h3>
                <p className="text-sm text-slate-500 lg:leading-relaxed mb-5">{s.desc}</p>

                {/* Pill preview card */}
                <div className="bg-slate-50 border border-slate-200/80 rounded-xl p-3.5">
                  <div className="text-[9px] font-bold uppercase tracking-widest mb-1.5" style={{ color: s.color }}>{s.highlight}</div>
                  <p className="text-[11px] text-slate-600 font-medium italic">{s.pill}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ═══════════════ TESTIMONIALS ═══════════════ */}
      <section className="testimonials-sec py-10 lg:py-16 bg-white">
        <div className="container mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <div className="text-center lg:mb-10 mb-6 space-y-4">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-rose-500/10 text-rose-500 text-[11px] font-bold uppercase tracking-widest border border-rose-500/20">
              <Heart className="h-3.5 w-3.5" /> Traveler Reviews
            </div>
            <h2 className="text-2xl sm:text-3xl md:text-5xl font-bold font-display">
              Loved by solo travelers{" "}
              <span className="text-primary">&amp; agencies.</span>
            </h2>
            <p className="text-slate-500 lg:text-base text-sm max-w-xl mx-auto lg:leading-relaxed">
              Real experiences from real travelers across India.
            </p>
          </div>

          <Swiper
            modules={[Autoplay, Pagination]}
            spaceBetween={20}
            slidesPerView={1}
            loop={true}
            autoplay={{ delay: 3500, disableOnInteraction: false }}
            pagination={{ clickable: true, dynamicBullets: true }}
            breakpoints={{
              640: { slidesPerView: 2, spaceBetween: 20 },
              1024: { slidesPerView: 3, spaceBetween: 24 },
            }}
            className="testimonials-swiper sm:!pb-12 !pb-8"
          >
            {TESTIMONIALS.map((t: any) => (
              <SwiperSlide key={t.name} className="h-auto">
                <div className="h-full flex flex-col justify-between group px-1">
                  {/* Quote card */}
                  <div className="relative bg-white border border-slate-200/80 rounded-2xl lg:p-6 sm:p-5 p-4 shadow-sm hover:shadow-md group-hover:border-primary/40 transition-all duration-300 flex-1 flex flex-col justify-between">
                    <div className="space-y-3">
                      {/* Stars */}
                      <div className="flex gap-0.5 text-primary">
                        {Array.from({ length: t.rating }).map((_: any, i: number) => (
                          <Star key={i} className="h-3.5 w-3.5 fill-current" />
                        ))}
                      </div>
                      <p className="text-sm text-slate-600 sm:leading-relaxed italic">&ldquo;{t.text}&rdquo;</p>
                    </div>
                    {/* Speech bubble tail */}
                    <div className="absolute -bottom-2 left-8 w-4 h-4 bg-white border-r border-b border-slate-200/80 rotate-45 group-hover:border-r-primary/40 group-hover:border-b-primary/40 transition-colors duration-300" />
                  </div>
                  {/* Author */}
                  <div className="flex items-center gap-3 mt-5 pl-5">
                    <img src={t.avatar} alt={t.name} className="h-10 w-10 rounded-full object-cover shrink-0 border-2 border-white shadow-sm" />
                    <div>
                      <h5 className="text-base font-bold text-slate-900 font-display leading-tight mb-1">{t.name}</h5>
                      <p className="text-[11px] text-slate-500 font-semibold uppercase tracking-wider mt-0.5">{t.role}</p>
                    </div>
                  </div>
                </div>
              </SwiperSlide>
            ))}
          </Swiper>
        </div>
      </section>

      {/* ═══════════════ FREQUENTLY ASKED QUESTIONS (FAQ) ═══════════════ */}
      <section id="faq" className="faq-sec py-10 lg:py-16 bg-slate-50 border-t border-slate-200/60 scroll-mt-16">
        <div className="container mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">

          <div className="grid grid-cols-1 md:grid-cols-12 lg:gap-12 gap-8 items-start">

            {/* Left sticky heading */}
            <div className="md:col-span-5 md:sticky md:top-28 md:text-start text-center">
              <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-secondary/10 border border-secondary/20 text-[11px] font-bold uppercase tracking-widest text-secondary mb-5">
                <HelpCircle className="h-3.5 w-3.5" /> FAQ
              </div>
              <h2 className="text-2xl sm:text-3xl md:text-5xl font-bold font-display mb-4">
                Frequently asked{" "}
                <span className="text-primary">questions.</span>
              </h2>
              <p className="text-slate-500 lg:text-base text-sm lg:leading-relaxed lg:mb-8 mb-6">
                Everything you need to know about AI itinerary generation, verified packages, and payment security.
              </p>
              <Link href="/contact">
                <Button variant="outline" className="border-slate-200 hover:border-primary hover:text-primary">
                  Ask a question <ArrowRight className="h-4 w-4" />
                </Button>
              </Link>
            </div>

            {/* Right FAQ accordion */}
            <div className="md:col-span-7 space-y-3">
              {FAQS.map((faq, index) => {
                const isOpen = openFaq === index;
                return (
                  <div
                    key={index}
                    className={`rounded-xl border transition-all duration-300 overflow-hidden ${isOpen
                      ? "border-primary/50 bg-orange-50/60 shadow-sm"
                      : "border-slate-200 bg-white hover:border-slate-300"
                      }`}
                  >
                    <button
                      type="button"
                      onClick={() => setOpenFaq(isOpen ? null : index)}
                      className="w-full md:px-6 sm:p-5 p-4 md:py-5 text-left flex items-center justify-between gap-3 cursor-pointer focus:outline-none"
                    >
                      <span className="flex items-center gap-3.5">
                        <span className={`h-6 w-6 rounded-full flex items-center justify-center text-[11px] font-bold shrink-0 transition-colors ${isOpen ? "bg-primary text-white" : "bg-slate-100 text-slate-500"
                          }`}>
                          {index + 1}
                        </span>
                        <span className="text-[14px] font-semibold text-slate-900 leading-snug">{faq.question}</span>
                      </span>
                      <ChevronDown
                        className={`h-5 w-5 shrink-0 text-slate-400 transition-transform duration-300 ${isOpen ? "rotate-180 text-primary" : ""
                          }`}
                      />
                    </button>

                    {isOpen && (
                      <div className="md:px-6 sm:p-5 p-4 md:pb-5 pt-0 text-[13px] text-slate-600 sm:leading-relaxed">
                        {faq.answer}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>

          </div>
        </div>
      </section>
      {/* ═══════════════ CTA SECTION ═══════════════ */}
      <section className="cta-sec py-10 lg:py-16 bg-white">
        <div className="container mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">

          {/* CTA card with gradient bg */}
          <div className="relative overflow-hidden rounded-3xl sm:p-8 p-5 lg:p-12"
            style={{ background: "linear-gradient(135deg, #1A3B5A 0%, #0f2540 60%, #1a2e3f 100%)" }}
          >
            <div className="relative z-10 grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-16 items-center">

              {/* Left column */}
              <div className="lg:space-y-6 space-y-5 lg:text-left text-center">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-primary/15 border border-primary/25 text-[10px] font-bold uppercase tracking-widest text-[#E8AA9B]">
                  <Sparkles className="h-3 w-3" /> Gemini AI
                </div>

                <div>
                  <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-white leading-[1.15] font-display mb-3">
                    Plan smarter.{" "}
                    <span className="bg-gradient-to-r from-primary via-[#E8AA9B] to-secondary bg-clip-text text-transparent">
                      Travel better.
                    </span>
                  </h2>
                  <p className="text-slate-400 text-sm sm:leading-relaxed lg:max-w-md max-w-xl lg:mx-0 mx-auto">
                    Generate a complete day-by-day itinerary from a single sentence, then book directly with verified agencies — in under 60 seconds.
                  </p>
                </div>

                <div className="flex flex-col sm:flex-row items-center lg:justify-start justify-center gap-3">
                  <Link href="/trip-builder">
                    <Button className="py-3 px-5">
                      <Sparkles className="h-4 w-4" /> Start Free — AI Builder
                    </Button>
                  </Link>
                  <Link href="/packages">
                    <Button className="py-3 px-5 bg-white/8 border border-white/15 text-white/90 hover:bg-white/15">
                      Browse Packages <ArrowRight className="h-4 w-4" />
                    </Button>
                  </Link>
                </div>

                <div className="flex flex-wrap lg:justify-start justify-center gap-3 pt-1">
                  {[
                    { icon: Check, label: "Free AI Drafts" },
                    { icon: Star, label: "4.9 / 5 Rated" },
                    { icon: Shield, label: "Razorpay Secured" },
                  ].map(({ icon: Icon, label }) => (
                    <span key={label} className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-white/6 border border-white/10 text-[11px] font-medium text-slate-400">
                      <Icon className="h-3 w-3 text-[#E8AA9B]" /> {label}
                    </span>
                  ))}
                </div>
              </div>

              {/* Right column — compact AI preview */}
              <div className="lg:block hidden bg-slate-900/60 backdrop-blur-sm border border-slate-700/50 rounded-2xl p-5 space-y-4">
                <div className="flex items-center justify-between pb-3 border-b border-slate-800/80">
                  <div className="flex items-center gap-2">
                    <span className="relative flex h-2.5 w-2.5">
                      <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75" />
                      <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-primary" />
                    </span>
                    <span className="text-[11px] font-semibold text-slate-300">Gemini AI · Generating plan</span>
                  </div>
                  <span className="text-[9px] font-bold uppercase tracking-widest px-2 py-0.5 rounded-full bg-white/15 text-white border border-white/25">Live</span>
                </div>

                <div className="bg-slate-900 rounded-xl p-3.5 border border-slate-800/60">
                  <div className="text-[9px] font-bold text-[#E8AA9B] uppercase tracking-widest mb-1.5">Traveler Prompt</div>
                  <p className="text-[12px] text-slate-300 italic leading-relaxed">
                    &ldquo;5-day Manali adventure with paragliding, hot springs &amp; trout dining under ₹15,000&rdquo;
                  </p>
                </div>

                <div className="grid grid-cols-3 gap-2">
                  {[
                    { label: "Duration", value: "5 Days" },
                    { label: "Est. Cost", value: "₹14,999" },
                    { label: "Generated", value: "24 sec" },
                  ].map(({ label, value }) => (
                    <div key={label} className="bg-slate-900/80 rounded-xl p-2.5 text-center border border-slate-800/60">
                      <div className="text-[9px] text-slate-500 font-semibold mb-0.5">{label}</div>
                      <div className="text-[13px] font-bold text-white">{value}</div>
                    </div>
                  ))}
                </div>

                <div className="space-y-2">
                  {[
                    { day: "Day 1", act: "Solang Valley + Paragliding" },
                    { day: "Day 2", act: "Beas Kund Glacier Trek" },
                    { day: "Day 3", act: "Old Manali Café &amp; Bonfire" },
                  ].map(({ day, act }) => (
                    <div key={day} className="flex items-center gap-2.5 text-[11px]">
                      <span className="text-primary font-bold shrink-0 w-10">{day}</span>
                      <div className="flex-1 h-px bg-slate-800" />
                      <span className="text-slate-400 font-medium" dangerouslySetInnerHTML={{ __html: act }} />
                    </div>
                  ))}
                </div>

                <Link href="/trip-builder" className="block">
                  <Button className="w-full bg-gradient-to-r from-primary to-[#E8AA9B]">
                    Try It Free <ArrowRight className="h-3.5 w-3.5" />
                  </Button>
                </Link>
              </div>

            </div>
          </div>
        </div>
      </section>

      {/* ═══════════════ FOOTER ═══════════════ */}
      <SiteFooter />
    </div>
  );
}
